return {
  -- {
  --   "nvim-lualine/lualine.nvim",
  --   dependencies = { "nvim-tree/nvim-web-devicons", "folke/snacks.nvim", "folke/noice.nvim" },
  --   config = function()
  --     local icons = require("config.icons")
  --     local Snacks = require("snacks")
  --     require("lualine").setup({
  --       sections = {
  --         lualine_a = { "mode" },
  --         lualine_b = { "branch" },
  --         lualine_c = {
  --           -- LazyVim.lualine.root_dir(),
  --           {
  --             "diagnostics",
  --             symbols = {
  --               error = icons.diagnostics.Error,
  --               warn = icons.diagnostics.Warn,
  --               info = icons.diagnostics.Info,
  --               hint = icons.diagnostics.Hint,
  --             },
  --           },
  --           { "filetype", icon_only = true, separator = "", padding = { left = 1, right = 0 } },
  --           {
  --             "filename",
  --             file_status = true, -- Displays file status (readonly status, modified status)
  --             newfile_status = false, -- Display new file status (new file means no write after created)
  --             path = 1, -- 0: Just the filename
  --             -- 1: Relative path
  --             -- 2: Absolute path
  --             -- 3: Absolute path, with tilde as the home directory
  --             -- 4: Filename and parent dir, with tilde as the home directory
  --
  --             shorting_target = 40, -- Shortens path to leave 40 spaces in the window
  --             -- for other components. (terrible name, any suggestions?)
  --             symbols = {
  --               modified = "[+]", -- Text to show when the file is modified.
  --               readonly = "[-]", -- Text to show when the file is non-modifiable or readonly.
  --               unnamed = "[No Name]", -- Text to show for unnamed buffers.
  --               newfile = "[New]", -- Text to show for newly created file before first write
  --             },
  --           },
  --         },
  --         lualine_x = {
  --           Snacks.profiler.status(),
  --       -- stylua: ignore
  --       {
  --         function() return require("noice").api.status.command.get() end,
  --         cond = function() return package.loaded["noice"] and require("noice").api.status.command.has() end,
  --         color = function() return { fg = Snacks.util.color("Statement") } end,
  --       },
  --       -- stylua: ignore
  --       {
  --         function() return require("noice").api.status.mode.get() end,
  --         cond = function() return package.loaded["noice"] and require("noice").api.status.mode.has() end,
  --         color = function() return { fg = Snacks.util.color("Constant") } end,
  --       },
  --       -- stylua: ignore
  --       {
  --         function() return "  " .. require("dap").status() end,
  --         cond = function() return package.loaded["dap"] and require("dap").status() ~= "" end,
  --         color = function() return { fg = Snacks.util.color("Debug") } end,
  --       },
  --       -- stylua: ignore
  --       {
  --         require("lazy.status").updates,
  --         cond = require("lazy.status").has_updates,
  --         color = function() return { fg = Snacks.util.color("Special") } end,
  --       },
  --           {
  --             "diff",
  --             symbols = {
  --               added = icons.git.added,
  --               modified = icons.git.modified,
  --               removed = icons.git.removed,
  --             },
  --             source = function()
  --               local gitsigns = vim.b.gitsigns_status_dict
  --               if gitsigns then
  --                 return {
  --                   added = gitsigns.added,
  --                   modified = gitsigns.changed,
  --                   removed = gitsigns.removed,
  --                 }
  --               end
  --             end,
  --           },
  --         },
  --         lualine_y = {
  --           { "progress", separator = " ", padding = { left = 1, right = 0 } },
  --           { "location", padding = { left = 0, right = 1 } },
  --         },
  --         lualine_z = {
  --           function()
  --             return " " .. os.date("%R")
  --           end,
  --         },
  --       },
  --     })
  --   end,
  -- },
}
